### ISSUE TITLE
Add performance tests for GPM IMERG and MUR SST using CMRBackend from titiler-cmr

### ISSUE THREAD

**Issue by maxrjones** [developmentseed/tile-benchmarking#49]
## Overview

This repository currently hosts performance tests for generating tiles from COGs, Zarr, and kerchunked NetCDFs using [titiler-pgstack](https://github.com/stac-utils/titiler-pgstac/). The goal of this issue is to establish a comparable performance tests for generating tiles from [GPM IMERG](https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGDE.07/) and [MUR-SST](https://podaac.jpl.nasa.gov/dataset/MUR-JPL-L4-GLOB-v4.1/) NetCDFs using [titiler-cmr](https://github.com/developmentseed/titiler-cmr).

## TODO

- [x] Create `CMRTileTest` in `02-run-tests/cmr_tile_test.py` with analoguous functionality to `CogTileTest` and `XarrayTileTest`
    - [x] connect to CMR
    - [x] generate arguments for creating a random tile
    - [x] generate a tile
- [x] Add notebook to run tests on GPM-IMERG datasets
- [x] Add notebook to run tests on MUR-SST
- [x] Run 10 iterations on each zoom level, storing the random tile IDs for reproducibility and results on s3
- [x] Plot the amount of time to generate the tile grouped by zoom level and dataset

#### GPM IMERG
```
dimensions:
	lon = 3600 ;
	lat = 1800 ;
	time = 1 ;
	nv = 2 ;
variables:
	float lon(lon) ;
		string lon:units = "degrees_east" ;
		string lon:long_name = "Longitude" ;
	double lat(lat) ;
		string lat:units = "degrees_north" ;
		string lat:long_name = "Latitude" ;
	double time(time) ;
		string time:units = "days since 1980-01-06 00:00:00Z" ;
		string time:standard_name = "time" ;
		string time:long_name = "time" ;
		string time:bounds = "time_bnds" ;
	double time_bnds(time, nv) ;
		string time_bnds:units = "days since 1980-01-06 00:00:00Z" ;
		string time_bnds:coordinates = "time nv" ;
```

#### MUR SST

```
dimensions:
dimensions:
	time = 1 ;
	lat = 17999 ;
	lon = 36000 ;
variables:
	int time(time) ;
		time:long_name = "reference time of sst field" ;
		time:standard_name = "time" ;
		time:axis = "T" ;
		time:units = "seconds since 1981-01-01 00:00:00 UTC" ;
		time:comment = "Nominal time of analyzed fields" ;
	float lat(lat) ;
		lat:long_name = "latitude" ;
		lat:standard_name = "latitude" ;
		lat:axis = "Y" ;
		lat:units = "degrees_north" ;
		lat:valid_min = -90.f ;
		lat:valid_max = 90.f ;
		lat:comment = "geolocations inherited from the input data without correction" ;
	float lon(lon) ;
		lon:long_name = "longitude" ;
		lon:standard_name = "longitude" ;
		lon:axis = "X" ;
		lon:units = "degrees_east" ;
		lon:valid_min = -180.f ;
		lon:valid_max = 180.f ;
		lon:comment = "geolocations inherited from the input data without correction" ;
```
