### ISSUE TITLE
titiler-pgstac and titiler-xarray code profiling using CMIP6 Daily TAS on AWS PDS

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/tile-benchmarking#5]
Execution of the work described in https://github.com/stac-utils/titiler-pgstac/discussions/97, specifically https://github.com/stac-utils/titiler-pgstac/discussions/97#discussioncomment-5981113, copying most content that discussion.

# Description

We would like to compare performance of tiling the same dataset using titiler-pgstac (COGs) and titiler-xarray (Zarr)

We believe this is the best approximation of comparing tiling between the two approaches because of the following methodology: 
1. Assume you are starting with a known collection
2. Metadata read step
    a. For COG: you register a query with pgstac for the collection id, variable and time step of interest
    b. For Zarr: You read consolidated metadata and "lazily load" the variable and time step (slice) of interest
    c. For now - I'm going to store both of these metadata components (pgstac and kerchunk reference) locally, but it might be of interest to move pgSTAC and kerchunk to the cloud...
3. Generate tiles
    a. COG: use mosaic ID to read chunks from COGs on S3
    b. Zarr: Use zarr metadata to read chunks from NetCDFs or Zarrs on S3

There is a public archive of COGs generated for CMIP6 for a VEDA related dashboard, using NetCDFs we have stored in S3 as well. There is a public archive is here: https://nex-gddp-cmip6-cog.s3.us-west-2.amazonaws.com/ and we have the original NetCDFs in S3 as well. So we can:

For titiler-pgstac:

- [x] Seed a pgSTAC collection of these files (started on this for https://nex-gddp-cmip6-cog.s3.us-west-2.amazonaws.com/index.html#monthly/CMIP6_ensemble_median/tas/ (2,808 entries))
- [x] Determine how to generate a mosaic + tile request
- [x] Write profiling code for titiler-pgstac for a single tile
- [x] #20
- [x] #16

For titiler-xarray

- [x] Create a kerchunk reference for the NetCDFs in S3
- [x] Write profiling code for titiler-xarray for a single tile (this is already started in https://github.com/developmentseed/titiler-xarray/pull/4)
- [x] #19
- [x] #17
- [x] #25
- [x] Create different chunking + pyramiding zarr stores
- [x] Run tests + report
- [ ] (Maybe) Test with higher resolution dataset

For both:
- [x] #21
- [x] #24

**Comment by abarciauskas-bgse** [comment]
Done
